### ISSUE TITLE
Container expiration not updated on checkout

### ISSUE THREAD

**Issue by jchristi** [seandst/webdriver-wharf#3]
I've had several occasions where containers where destroyed prematurely. I expected that after checkout, they would not be forcefully destroyed until TIMEOUT was reach (starting from the time I checked out the container). However, the behavior appears to be that the container is destroyed based on when it was created to the TIMEOUT limit regardless of checkout status.

**Comment by seandst** [comment]
This was *probably* fixed in https://github.com/seandst/webdriver-wharf/commit/96f788d2d021fdc1386ad0a47b98ddb1ae68a0f9
